spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
server:
  port: 8765
eureka:
  instance:
    hostname: 172.20.10.2
  client:
    service-url:
      default-zone: http://172.20.10.2:8761/eureka
    register-with-eureka: true
    fetch-registry: true
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5
