spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://host.docker.internal:8080/auth/realms/spring-boot-realm/protocol/openid-connect/token/introspect
          client-id: api-gateway
          client-secret: 4a78bb0b-988e-4bc8-8f7a-a32b66bbd321
server:
  port: 8765
eureka:
  instance:
    hostname: host.docker.internal
  client:
    service-url:
      default-zone: http://host.docker.internal:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5