spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/auth/realms/spring-boot-realm/protocol/openid-connect/token/introspect
          client-id: my-client-id
          client-secret: H9Go2mW1b0TOkeDkLtZRDqn058OSz2CM
server:
  port: 8765
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5